server:
  port: 0

spring:
  application:
    name: customer-service

  data:
    mongodb:
      host: localhost
      port: 27017
      database: customerdb

  rabbitmq:
    host: localhost
    port: 5672
    username: mark
    password: password
    template:
      routing-key: customer_key
      exchange: crm

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      default-zone:
        - http://localhost:8761/eureka/

logging:
  level:
    web: debug
  file:
    name: ./log/customer-service